### ISSUE TITLE
Can't delete wrongsizedfiles

### ISSUE THREAD

**Issue by ghost** [Wintermute0110/torrentverify#3]
Debian 7 with python 2.7 & python 3.4 tested

Here's what happens when I ran with the --deleteWrongSizeFiles

Delete this file? [y/N/a] y
File deleted
Traceback (most recent call last):
  File "torrentverify.py", line 996, in <module>
    ret_value = check_torrent_files_only(torrent_obj)
  File "torrentverify.py", line 471, in check_torrent_files_only
    os.unlink(torrent.file_length_list[i])
TypeError: unlink: illegal type for path parameter

All the other actions like : checkunneeded & truncatewrongsizedfiles work properly . 

Maybe the issues are because the filenames contain spaces , commas and parenthesis symbols .

**Comment by Wintermute0110** [comment]
Thanks for the report, I will have a look ASAP.

**Comment by drewdoggy** [comment]
Yes it's pretty obvious why it's not working, I'm surprised its been 3 years with nobody noticing! I only used torrentverify.py for the first time this evening.

The fix is to change line 471 from 

`os.unlink(torrent.file_length_list[i])`

to

`os.unlink(filename_path)`

**Comment by Wintermute0110** [comment]
Mmm... I have been using torrentverify myself for several years and it works well. I though the reason was wrong characters in the filenames. I will test ASAP.

**Comment by ghost** [comment]
That's great ! I just tested it and it works ! 
Thank you drewdoggy for the help !
